language: node_js
node_js:
  - "5.5"

install:
 - "npm install gitbook -g"
 - "npm install -g gitbook-cli"
script:
 - "gitbook build"
after_script:
  - sudo python gen.py
  - gitbook build
  - cp ./_book/* . -rf
  - rm _book -rf
  - git remote add builds "https://${GH_TOKEN}@${GH_REF}" 
  - git fetch builds
  - git config user.name "travis"
  - git config user.email ""
  - git checkout master
  - git add .
  - git commit -m "Build"
  - git branch -a
  - git log remotes/builds/master
  - git log 
  - git push -f builds master:gh-pages

env:
  global:
    - GH_REF: github.com/AceSrc/StayReal.git
